ALTER TABLE products 
ADD COLUMN IF NOT EXISTS unit_type TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS unit_value NUMERIC DEFAULT NULL,
ADD COLUMN IF NOT EXISTS unit_label TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS quantity_per_unit INTEGER DEFAULT NULL;

CREATE INDEX IF NOT EXISTS idx_products_unit_type ON products(unit_type);